version: '3.8'

services:
  ats:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - chroma_data:/mnt/ebs
    restart: unless-stopped

volumes:
  chroma_data:
    external: true
